### ISSUE TITLE
Typo in "Detection & Mitigation"

### ISSUE THREAD

**Issue by pensivepaddle** [trustedsec/specula#1]
Minor typo in the wiki for [Detection & Mitigation](https://github.com/trustedsec/specula/wiki/Detection-%26-Mitigation), with an extra `i` in `WebView` (`Webiview`).

Thanks for the great docs and writeup!

**Comment by api0cradle** [comment]
Great catch! Sorry about that. Should be fixed now. Thanks for notifying us
