### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by russokiwi** [trustedsec/specula#2]
On loading of the script getting a:

"Script Error" msgbox

`Line: 93
Char: 1
Error: Expected statement
Code: 0
URL: the long URL`

This then occurs (same error though different URL) every time I switch back to inbox from calendar, or every time a call back is made.  full registry import as generated by generatehooker.   

Outlook version - latest o365.

How can I fix?  Thanks!

**Comment by freefirex** [comment]
Please post the contents of a .reg file produced by generatehooker that can reproduce this issue and we'll look into it.

**Comment by russokiwi** [comment]
Thank you!  

`Windows Registry Editor Version 5.00
        
[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\16.0\Outlook\Webview\Inbox]
"url"="https://mail.domainredacted.com/plugin/search/"
"security"="yes"

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\15.0\Outlook\Webview\Inbox]
"url"="https://mail.domainredacted.com/plugin/search/"
"security"="yes"

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\14.0\Outlook\Webview\Inbox]
"url"="https://mail.domainredacted.com/plugin/search/"
"security"="yes"

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Ext\Stats\{261B8CA9-3BAF-4BD0-B0C2-BF04286785C6}\iexplore]
"Flags"=dword:00000004

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\2]
"140C"=dword:00000000
"1200"=dword:00000000
"1201"=dword:00000003`

**Comment by freefirex** [comment]
I'm unable to reproduce the issue you are stating using that reg file.

To test I

1. cloned Specula from this repository
2. configured a trusted CA cert for the domain mail.domainredacted.com
3. ran through specula config specifying mail.domainredacted.com, leaving default plugin/search as you have and leaving other options default outside of pointing at my trusted cert / private key
4. Launched a windows VM and configured the host files such that mail.domainredacted.com pointed at my Specula server
5. Installed the .reg file
6. Launched outlook

In my case outlook was able to properly connect and stage into a full agent.

My outlook version is also a fully up to date Office 365 install of outlook.

Is there any additional information you believe I should consider or that you think may be affecting this?

**Comment by russokiwi** [comment]
those are the steps I took, my setup though is through cloudflare reverse proxy, and then an nginx reverse proxy which I wouldn't think would make much difference.  Anyway, I just used one of my other domains and issue seems to have been resolved.  I've no idea why that is, it makes no sence but I suppose it doesn't matter - it's working now.  Thanks very much for you time, please close the ticket.
